const app = document.querySelector('#app');
let state;
const escapeHtml = (value = '') => String(value).replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[character]));
function stage() { return state.currentStep < 0 ? 'opening' : state.currentStep >= state.runbook.steps.length ? 'closing' : 'product'; }
function applyTheme() { const t = state.theme.tokens; Object.entries(t).forEach(([key, value]) => document.documentElement.style.setProperty(`--${key.replace(/[A-Z]/g, (x) => `-${x.toLowerCase()}`)}`, value)); }
function render() {
  applyTheme(); const currentStage = stage(); const step = state.runbook.steps[state.currentStep];
  if (currentStage === 'opening') app.innerHTML = `<section class="hero" data-demo-stage="opening"><p class="eyebrow">${escapeHtml(state.theme.productName)}</p><h1>${escapeHtml(state.runbook.opening.title)}</h1><p>${escapeHtml(state.runbook.opening.subtitle)}</p><button data-demo-control="open-product">Open live product</button><button class="quiet" data-demo-control="notes">Presenter notes</button></section>`;
  else if (currentStage === 'closing') app.innerHTML = `<section class="hero" data-demo-stage="closing"><p class="eyebrow">${escapeHtml(state.theme.productName)}</p><h1>${escapeHtml(state.runbook.closing.title)}</h1><p>${escapeHtml(state.runbook.closing.takeaway)}</p><button class="quiet" data-demo-control="previous">Previous</button><button class="quiet" data-demo-control="notes">Presenter notes</button></section>`;
  else app.innerHTML = `<section class="product" data-demo-stage="product"><header><span class="chapter" data-demo-current-step="${escapeHtml(step.id)}">${state.currentStep + 1}. ${escapeHtml(step.title)}</span><span class="status" data-demo-browser-status="${state.browser.status}">${escapeHtml(state.browser.status)}</span><button class="quiet" data-demo-control="notes">Presenter notes</button></header><nav class="browser"><button data-demo-control="back">←</button><button data-demo-control="forward">→</button><button data-demo-control="reload">Reload</button><input aria-label="Live product URL" data-demo-control="address" value="${escapeHtml(state.browser.address)}"><button data-demo-control="go">Go</button><button data-demo-control="retry" data-demo-retry-mode="ignore-cache">Retry</button></nav><p class="browser-error" data-demo-browser-error>${escapeHtml(state.browser.error)}</p><div id="browser-slot"></div><footer><button class="quiet" data-demo-control="previous">Previous</button><button class="quiet" data-demo-control="next">Next</button></footer></section>`;
  bind(); requestAnimationFrame(setBounds);
}
function setBounds() { const slot = document.querySelector('#browser-slot'); if (!slot) return window.demo.setBrowserBounds({ x: 0, y: 0, width: 0, height: 0 }); const rect = slot.getBoundingClientRect(); window.demo.setBrowserBounds({ x: rect.x, y: rect.y, width: rect.width, height: rect.height }); }
function bind() { const control = (name, handler) => document.querySelector(`[data-demo-control="${name}"]`)?.addEventListener('click', handler); control('open-product', () => window.demo.next()); control('previous', () => window.demo.previous()); control('next', () => window.demo.next()); control('notes', () => window.demo.openNotes()); control('back', () => window.demo.back()); control('forward', () => window.demo.forward()); control('reload', () => window.demo.reload()); control('retry', () => window.demo.retry()); control('go', () => window.demo.navigate(document.querySelector('[data-demo-control="address"]').value)); }
window.addEventListener('resize', setBounds); window.demo.onState((next) => { state = next; render(); }); window.demo.getState().then((next) => { state = next; render(); });
